FROM node:20-alpine AS base

WORKDIR /app

COPY package*.json ./
COPY tsconfig.base.json ./
COPY apps/api/package*.json ./apps/api/

RUN npm install --workspaces=false
RUN npm install --workspace=apps/api

COPY apps/api ./apps/api

WORKDIR /app/apps/api
RUN npm run build

EXPOSE 4491

CMD ["npm", "start"]
